title: "Pedro Angulo-Umana, Ph.D"
name: "Pedro"
description: "Tropical meteorology · Atmospheric convection · "
url: "https://pedroanguloumana.github.io/"
baseurl: ""  # keep empty for user.github.io site

markdown: kramdown
collections:
  pages:
    output: true
    permalink: /:path/
    
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes specific:
minimal_mistakes_skin: "sunrise" # or "air", "contrast", etc.


author:
  # name: "Your Name"
  # bio: "Short 1–2 sentence bio about your research."
  avatar: "assets/images/headshot_scaled.png"
